import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  static const String _languageKey = 'language';
  
  Locale _locale = const Locale('fr');
  
  Locale get locale => _locale;
  String get languageCode => _locale.languageCode;
  bool get isFrench => _locale.languageCode == 'fr';

  LanguageProvider() {
    _loadLanguage();
  }

  void setLanguage(String languageCode) {
    _locale = Locale(languageCode);
    _saveLanguage();
    notifyListeners();
  }

  void toggleLanguage() {
    _locale = _locale.languageCode == 'fr' 
        ? const Locale('en') 
        : const Locale('fr');
    _saveLanguage();
    notifyListeners();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString(_languageKey) ?? 'fr';
    _locale = Locale(languageCode);
    notifyListeners();
  }

  Future<void> _saveLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, _locale.languageCode);
  }

  // Translations
  Map<String, String> get translations => _locale.languageCode == 'fr' 
      ? _frenchTranslations 
      : _englishTranslations;

  String translate(String key) {
    return translations[key] ?? key;
  }

  static const Map<String, String> _frenchTranslations = {
    'home': 'Accueil',
    'scan': 'Scanner',
    'manual_entry': 'Ajouter',
    'budget': 'Budget',
    'reports': 'Rapports',
    'settings': 'Paramètres',
    'receipt_scanner': 'Receipt Scanner',
    'recent_receipts': 'Reçus récents',
    'total_budget': 'Budget Total',
    'monthly_spending': 'Dépenses du mois',
    'no_receipts': 'Aucun reçu',
    'no_receipts_subtitle': 'Commencez par scanner un reçu ou en ajouter un manuellement',
    'scan_receipt': 'Scanner un reçu',
    'upload': 'Télécharger',
    'analyzing': 'Analyse en cours...',
    'add_receipt': 'Ajouter un reçu',
    'store_name': 'Nom du magasin',
    'date': 'Date',
    'category': 'Catégorie',
    'items': 'Articles',
    'add_item': 'Ajouter un article',
    'item_name': 'Nom de l\'article',
    'price': 'Prix',
    'quantity': 'Quantité',
    'subtotal': 'Sous-total',
    'tps': 'TPS (5%)',
    'tvq': 'TVQ (9.975%)',
    'total': 'Total',
    'save': 'Sauvegarder',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'back': 'Retour',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'dark_mode': 'Mode sombre',
    'language': 'Langue',
    'preferences': 'Préférences',
    'data_management': 'Gestion des données',
    'export_data': 'Exporter les données',
    'clear_all_data': 'Effacer toutes les données',
    'about': 'À propos',
    'version': 'Version',
    'see_all': 'Voir tout',
    'receipt_details': 'Détails de la facture',
    'this_month': 'Ce mois',
    'spent': 'Dépensé',
    'storage_used': 'Stockage utilisé',
    'storage_used_subtitle': 'Nombre de reçus : {count}',
    'export_csv': 'Exporter les reçus en CSV',
    'export_coming_soon': 'Fonction export bientôt disponible!',
    'delete_all_data_subtitle': 'Supprimer tous les reçus et données',
    'help_support': 'Aide & Support',
    'app_version': 'Version {version}',
    'footer_copyright': 'Receipt Scanner Flutter © {year}',
    'clear_all_data_confirm': 'Êtes-vous sûr de vouloir supprimer toutes les données ? Cette action est irréversible.',
    'clear_all_data_success': 'Toutes les données ont été supprimées avec succès',
    'clear_all_data_error': 'Erreur lors de la suppression des données',
    'month_format': '{month}',
    'current_month': 'En cours',
    'total_monthly_budget': 'Budget mensuel total',
    'percent_used': '{percent}% utilisé',
    'no_budget_set': 'Aucun budget défini',
    'add_at_least_one_item': 'Veuillez ajouter au moins un article',
    'enter_store_name': 'Veuillez entrer le nom du magasin',
    'receipt_saved_success': 'Facture sauvegardée avec succès',
    'receipt_updated': 'Facture mise à jour avec succès',
    'error_saving_receipt': 'Erreur lors de la sauvegarde de la facture',
    'tab_analysis': '📊 Analyse',
    'tab_ai': '🤖 IA',
    'tab_report': '📋 Rapport',
    'receipts': 'Reçus',
    'category_breakdown': 'Répartition par catégorie',
    'no_data_available': 'Aucune donnée disponible',
    'monthly_trend': 'Tendance mensuelle',
    'no_cameras_available': 'Aucune caméra disponible sur cet appareil',
    'failed_initialize_camera': 'Échec de l\'initialisation de la caméra',
    'failed_get_camera_list': 'Impossible d\'obtenir la liste des caméras',
    'failed_take_picture': 'Échec de la prise de photo',
    'failed_pick_image': 'Échec de la sélection de l\'image',
    'failed_process_receipt': 'Échec du traitement du reçu',
    'receipt_processed_success': 'Reçu traité avec succès!',
    'help_welcome': 'Bienvenue dans Receipt Scanner!',
    'help_features_title': 'Fonctionnalités principales :',
    'help_features_scan': '• Scanner une facture : Prenez une photo ou importez une image de votre reçu. L\'IA extrait automatiquement les informations importantes (date, montant, commerçant, articles, taxes, etc.).',
    'help_features_manual': '• Ajout manuel : Saisissez une facture à la main si la photo n\'est pas disponible ou si vous souhaitez corriger/compléter les informations.',
    'help_features_analysis': '• Analyse et rapports : Consultez vos dépenses par mois, par catégorie, ou par commerçant. Visualisez vos budgets et comparez vos dépenses réelles.',
    'help_features_budget': '• Budgets : Définissez un budget mensuel global ou par catégorie. Suivez votre progression et recevez des alertes si vous dépassez vos limites.',
    'help_features_export': '• Export : Exportez vos reçus au format CSV pour les utiliser dans d\'autres applications.',
    'help_examples_title': 'Exemples d\'utilisation :',
    'help_example_scan_groceries': '• Après vos courses, scannez le ticket pour suivre vos dépenses alimentaires.',
    'help_example_manual_online': '• Ajoutez manuellement une facture d\'achat en ligne reçue par email.',
    'help_example_monthly_report': '• Consultez le rapport mensuel pour voir où va votre argent.',
    'help_example_budget_restaurant': '• Fixez un budget "Restaurants" et surveillez vos sorties.',
    'help_need_help': 'Besoin d\'aide ?',
    'help_contact': '• Pour toute question ou suggestion, contactez-nous via la page de support ou consultez la FAQ sur notre site.',
    'category_shopping': 'Magasinage',
    'category_food': 'Alimentation',
    'category_transport': 'Transport',
    'category_entertainment': 'Loisirs',
    'category_health': 'Santé',
    'category_home': 'Maison',
    'general_info': 'Informations générales',
    'summary': 'Résumé',
    'notes_optional': 'Notes (optionnel)',
    'add_notes': 'Ajouter des notes sur ce reçu...',
    'saving': 'Sauvegarde en cours...',
    'item': 'Article',
    'prices_include_tax': 'Les prix incluent les taxes',
    'edit_budget': 'Modifier le budget',
    'save_budget': 'Enregistrer le budget',
    'budget_per_category': 'Budget par catégorie',
    'spent_this_month': 'Dépensé ce mois-ci',
    'budget_amount': 'Montant du budget',
    'enter_budget_amount': 'Entrez le montant du budget',
    'budget_updated': 'Budget mis à jour',
    'budget_update_error': 'Erreur lors de la mise à jour du budget',
    'delete_receipt': 'Supprimer la facture',
    'delete_receipt_confirmation': 'Êtes-vous sûr de vouloir supprimer cette facture ? Cette action ne peut pas être annulée.',
    'notes': 'Notes',
    'edit_receipt': 'Modifier la facture',
    'receipt_not_found': 'Facture non trouvée',
  };

  static const Map<String, String> _englishTranslations = {
    'home': 'Home',
    'scan': 'Scan',
    'manual_entry': 'Add',
    'budget': 'Budget',
    'reports': 'Reports',
    'settings': 'Settings',
    'receipt_scanner': 'Receipt Scanner',
    'recent_receipts': 'Recent Receipts',
    'total_budget': 'Total Budget',
    'monthly_spending': 'Monthly Spending',
    'no_receipts': 'No Receipts',
    'no_receipts_subtitle': 'Start by scanning a receipt or adding one manually',
    'scan_receipt': 'Scan Receipt',
    'upload': 'Upload',
    'analyzing': 'Analyzing...',
    'add_receipt': 'Add Receipt',
    'store_name': 'Store Name',
    'date': 'Date',
    'category': 'Category',
    'items': 'Items',
    'add_item': 'Add Item',
    'item_name': 'Item Name',
    'price': 'Price',
    'quantity': 'Quantity',
    'subtotal': 'Subtotal',
    'tps': 'GST (5%)',
    'tvq': 'PST (9.975%)',
    'total': 'Total',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'back': 'Back',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'preferences': 'Preferences',
    'data_management': 'Data Management',
    'export_data': 'Export Data',
    'clear_all_data': 'Clear All Data',
    'about': 'About',
    'version': 'Version',
    'see_all': 'See All',
    'receipt_details': 'Receipt Details',
    'this_month': 'This month',
    'spent': 'Spent',
    'storage_used': 'Storage Used',
    'storage_used_subtitle': 'Number of receipts: {count}',
    'export_csv': 'Export receipts as CSV',
    'export_coming_soon': 'Export feature coming soon!',
    'delete_all_data_subtitle': 'Delete all receipts and data',
    'help_support': 'Help & Support',
    'app_version': 'Version {version}',
    'footer_copyright': 'Receipt Scanner Flutter © {year}',
    'clear_all_data_confirm': 'Are you sure you want to delete all receipts and data? This action cannot be undone.',
    'clear_all_data_success': 'All data cleared successfully',
    'clear_all_data_error': 'Error clearing data',
    'month_format': '{month}',
    'current_month': 'Current',
    'total_monthly_budget': 'Total Monthly Budget',
    'percent_used': '{percent}% used',
    'no_budget_set': 'No budget set',
    'add_at_least_one_item': 'Please add at least one item',
    'enter_store_name': 'Please enter the store name',
    'receipt_saved_success': 'Receipt saved successfully',
    'receipt_updated': 'Receipt updated successfully',
    'error_saving_receipt': 'Error saving receipt',
    'tab_analysis': '📊 Analysis',
    'tab_ai': '🤖 AI',
    'tab_report': '📋 Report',
    'receipts': 'Receipts',
    'category_breakdown': 'Category Breakdown',
    'no_data_available': 'No data available',
    'monthly_trend': 'Monthly Trend',
    'no_cameras_available': 'No cameras available on this device',
    'failed_initialize_camera': 'Failed to initialize camera',
    'failed_get_camera_list': 'Failed to get camera list',
    'failed_take_picture': 'Failed to take picture',
    'failed_pick_image': 'Failed to pick image',
    'failed_process_receipt': 'Failed to process receipt',
    'receipt_processed_success': 'Receipt processed successfully!',
    'help_welcome': 'Welcome to Receipt Scanner!',
    'help_features_title': 'Main features:',
    'help_features_scan': '• Scan a receipt: Take a photo or import an image of your receipt. The AI automatically extracts important information (date, amount, merchant, items, taxes, etc.).',
    'help_features_manual': '• Manual entry: Enter a receipt by hand if the photo is not available or if you want to correct/complete the information.',
    'help_features_analysis': '• Analysis and reports: View your expenses by month, by category, or by merchant. Visualize your budgets and compare your actual spending.',
    'help_features_budget': '• Budgets: Set a global or category budget. Track your progress and get alerts if you exceed your limits.',
    'help_features_export': '• Export: Export your receipts as CSV for use in other applications.',
    'help_examples_title': 'Usage examples:',
    'help_example_scan_groceries': '• After shopping, scan the ticket to track your food expenses.',
    'help_example_manual_online': '• Manually add an online purchase receipt received by email.',
    'help_example_monthly_report': '• Check the monthly report to see where your money goes.',
    'help_example_budget_restaurant': '• Set a "Restaurants" budget and monitor your outings.',
    'help_need_help': 'Need help?',
    'help_contact': '• For any question or suggestion, contact us via the support page or check the FAQ on our website.',
    'category_shopping': 'Shopping',
    'category_food': 'Food',
    'category_transport': 'Transport',
    'category_entertainment': 'Entertainment',
    'category_health': 'Health',
    'category_home': 'Home',
    'general_info': 'General Information',
    'summary': 'Summary',
    'notes_optional': 'Notes (optional)',
    'add_notes': 'Add notes about this receipt...',
    'saving': 'Saving...',
    'item': 'Item',
    'prices_include_tax': 'Prices include taxes',
    'edit_budget': 'Edit Budget',
    'save_budget': 'Save Budget',
    'budget_per_category': 'Budget per Category',
    'spent_this_month': 'Spent this month',
    'budget_amount': 'Budget Amount',
    'enter_budget_amount': 'Enter budget amount',
    'budget_updated': 'Budget updated',
    'budget_update_error': 'Error updating budget',
    'delete_receipt': 'Delete Receipt',
    'delete_receipt_confirmation': 'Are you sure you want to delete this receipt? This action cannot be undone.',
    'notes': 'Notes',
    'edit_receipt': 'Edit Receipt',
    'receipt_not_found': 'Receipt not found',
  };
}